include: package:flutter_lints/flutter.yaml
linter:
  rules:
    prefer_const_constructors: true
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - bricks/**
  errors:
    invalid_annotation_target: ignore