name: connectinno_case
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  dio: ^5.9.0
  auto_route: ^10.2.0

  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  email_validator: ^3.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.5
  uuid: ^4.5.1
  logger: ^2.6.2
  flutter_secure_storage: ^9.2.4


  freezed_annotation: any
dependency_overrides: 
  freezed_annotation: ^3.1.0
  test: ^1.26.3
  test_api: 0.7.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.1
  json_serializable: ^6.11.1
  freezed: ^3.2.3
  auto_route_generator: ^10.2.5


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
