// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDobqDbG_3YD3Rq5KAh9o_Ku9LXoK0eEFk',
    appId: '1:639511730113:web:2bdac2b42cce2ee4f84140',
    messagingSenderId: '639511730113',
    projectId: 'connectinnocase-aced3',
    authDomain: 'connectinnocase-aced3.firebaseapp.com',
    storageBucket: 'connectinnocase-aced3.firebasestorage.app',
    measurementId: 'G-XDNKBNJ0P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYTZUAFwTwH4_HMS85XfXtF6iBMj-sr-U',
    appId: '1:639511730113:android:d32406bafdf5222ef84140',
    messagingSenderId: '639511730113',
    projectId: 'connectinnocase-aced3',
    storageBucket: 'connectinnocase-aced3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr_y9HExeic4YDTt5cWJCd1IPMfpEZuhM',
    appId: '1:639511730113:ios:ee2b5521d2530bbff84140',
    messagingSenderId: '639511730113',
    projectId: 'connectinnocase-aced3',
    storageBucket: 'connectinnocase-aced3.firebasestorage.app',
    iosBundleId: 'com.example.connectinnoCase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr_y9HExeic4YDTt5cWJCd1IPMfpEZuhM',
    appId: '1:639511730113:ios:ee2b5521d2530bbff84140',
    messagingSenderId: '639511730113',
    projectId: 'connectinnocase-aced3',
    storageBucket: 'connectinnocase-aced3.firebasestorage.app',
    iosBundleId: 'com.example.connectinnoCase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDobqDbG_3YD3Rq5KAh9o_Ku9LXoK0eEFk',
    appId: '1:639511730113:web:a10b7e31d04ad964f84140',
    messagingSenderId: '639511730113',
    projectId: 'connectinnocase-aced3',
    authDomain: 'connectinnocase-aced3.firebaseapp.com',
    storageBucket: 'connectinnocase-aced3.firebasestorage.app',
    measurementId: 'G-JXRC2CG76X',
  );
}
